//! Formatting utilities and parsers for the TUI interface.
//!
//! This module contains helper functions that transform raw application data into
//! visually appealing strings and `ratatui` styled text components. It handles visual
//! metadata generation (like project stack detection) and the bespoke, lightweight
//! Markdown-to-TUI text parser used to render the AI outputs.

use ratatui::{
    style::{Color, Modifier, Style},
    text::{Line, Span, Text},
};
use std::path::PathBuf;

/// Scans the provided list of files to infer the underlying project architecture.
///
/// This function iterates over the file extensions discovered during the directory
/// parsing phase. By identifying specific combinations of files (like `.rs` combined
/// with `.toml`), it can accurately guess the user's framework or stack. It outputs
/// a formatted, multi-line string containing relevant emojis to be displayed in the
/// "Project Meta" UI pane.
pub fn detect_project_stack(files: &[PathBuf]) -> String {
    let mut has_rs = false;
    let mut has_js = false;
    let mut has_py = false;
    let mut has_toml = false;

    for f in files {
        if let Some(ext) = f.extension() {
            match ext.to_str().unwrap_or("") {
                "rs" => has_rs = true,
                "js" | "ts" | "jsx" | "tsx" => has_js = true,
                "py" => has_py = true,
                "toml" => has_toml = true,
                _ => {}
            }
        }
    }

    let mut stack = Vec::new();
    if has_rs && has_toml {
        stack.push("Rust (Cargo)");
    }
    if has_js {
        stack.push("JS/TS (Node)");
    }
    if has_py {
        stack.push("Python");
    }

    if stack.is_empty() {
        "Unknown Stack".to_string()
    } else {
        stack.join("\n")
    }
}

/// Converts a raw Markdown string into styled, multi-colored Ratatui `Text` lines.
///
/// Rather than pulling in a massive, heavy Markdown rendering crate, this function
/// serves as a highly optimized, single-pass lexical scanner specifically tailored to
/// the outputs generated by the `AiClient` and `extractor`. It rapidly applies terminal
/// colors and bold/italic modifiers to headers, code blocks, and blockquotes so the
/// architectural outlines are highly readable.
pub fn format_markdown<'a>(content: &'a str) -> Text<'a> {
    let mut lines = Vec::new();
    let mut in_code_block = false;

    for line in content.lines() {
        // Toggle the code block state when encountering triple backticks
        if line.starts_with("```") {
            in_code_block = !in_code_block;
            lines.push(Line::from(Span::styled(
                line,
                Style::default().fg(Color::DarkGray),
            )));
            continue;
        }

        // Apply a distinct cyan color to all text inside a code block
        if in_code_block {
            lines.push(Line::from(Span::styled(
                line,
                Style::default().fg(Color::Cyan),
            )));
            continue;
        }

        // Apply bold modifiers and specific colors to Markdown Headers (#, ##, ###)
        if line.starts_with("### ") {
            lines.push(Line::from(Span::styled(
                line,
                Style::default()
                    .fg(Color::LightBlue)
                    .add_modifier(Modifier::BOLD),
            )));
        } else if line.starts_with("# ") || line.starts_with("## ") {
            lines.push(Line::from(Span::styled(
                line,
                Style::default()
                    .fg(Color::Blue)
                    .add_modifier(Modifier::BOLD),
            )));
        }
        // Format Docstrings and blockquotes (> ) with green italics and a visual vertical bar
        else if line.starts_with("> ") {
            let text = line.trim_start_matches("> ").trim_matches('*').trim();
            let mut spans = vec![Span::styled(" ┃ ", Style::default().fg(Color::DarkGray))];
            spans.push(Span::styled(
                text,
                Style::default()
                    .fg(Color::Green)
                    .add_modifier(Modifier::ITALIC),
            ));
            lines.push(Line::from(spans));
        }
        // Format Extracted Structs/Functions (**`) with a diamond emoji and bold yellow text
        else if line.starts_with("**`") {
            let text = line.trim_matches(|c| c == '*' || c == '`');
            lines.push(Line::from(Span::styled(
                format!("🔹 {}", text),
                Style::default()
                    .fg(Color::Yellow)
                    .add_modifier(Modifier::BOLD),
            )));
        }
        // Handle standard paragraph text, aggressively stripping raw markdown formatting markers
        // to keep the terminal output clean and readable.
        else {
            let clean_text = line.replace("**", "").replace('*', "").replace('`', "");
            lines.push(Line::from(Span::styled(
                clean_text,
                Style::default().fg(Color::White),
            )));
        }
    }
    Text::from(lines)
}
