//! Caching logic for AI-generated explanations to save tokens and reduce latency.
//!
//! This module provides a robust, file-system-based caching mechanism. Because analyzing
//! source code via LLMs can be expensive (in terms of tokens) and slow (in terms of network
//! latency), this cache ensures that identical file contents are only processed once.
//! It achieves this by generating cryptographic hashes of the file contents to use as unique
//! lookup keys.

use crate::errors::OnboarderError;
use sha2::{Digest, Sha256};
use std::fs;
use std::path::{Path, PathBuf};

/// Manages caching of AI-generated explanations to save processing tokens.
///
/// The `CacheManager` abstracts file system operations to read, write, and manage
/// Markdown summaries generated by the AI client. It guarantees that the cache
/// directory exists upon instantiation and safely handles read/write operations.
pub struct CacheManager {
    /// The absolute or relative directory path where markdown explanations are stored.
    pub cache_dir: PathBuf,
}

impl CacheManager {
    /// Creates a new `CacheManager` bound to the specified cache directory.
    ///
    /// Upon initialization, this function proactively attempts to create the target
    /// directory (and any necessary parent directories) if it does not already exist.
    /// This prevents runtime IO errors when attempting to save the first cached file.
    pub fn new(cache_dir: PathBuf) -> Result<Self, OnboarderError> {
        fs::create_dir_all(&cache_dir)?;
        Ok(Self { cache_dir })
    }

    /// Retrieves the path to the currently configured cache directory.
    ///
    /// This is a read-only convenience method to inspect the storage location
    /// without consuming or directly exposing the inner `PathBuf`.
    #[allow(dead_code)]
    pub fn cache_dir(&self) -> &Path {
        &self.cache_dir
    }

    /// Attempts to retrieve a previously cached explanation for a given file hash.
    ///
    /// This function performs a disk lookup for a `.md` file matching the provided
    /// SHA-256 hash. If the file exists and is readable, it loads the entire contents
    /// into a String and returns it.
    ///
    /// Returns `Some(content)` if the cache hit is successful, or `None` if the file
    /// is missing or unreadable.
    pub fn get_cached_explanation(&self, file_hash: &str) -> Option<String> {
        let cache_file = self.cache_dir.join(format!("{}.md", file_hash));
        if cache_file.exists() {
            fs::read_to_string(cache_file).ok()
        } else {
            None
        }
    }

    /// Saves a newly generated AI explanation to the cache directory.
    ///
    /// The content is written out as a Markdown file, named exactly after the
    /// file's SHA-256 hash (e.g., `a1b2c3d4...e5f6.md`). If a file with this name
    /// already exists, it will be silently overwritten with the new content.
    pub fn save_explanation(&self, file_hash: &str, content: &str) -> Result<(), OnboarderError> {
        let cache_file = self.cache_dir.join(format!("{}.md", file_hash));
        fs::write(cache_file, content)?;
        Ok(())
    }

    /// Completely wipes all cached explanations from the disk.
    ///
    /// This function aggressively deletes the entire cache directory and all its
    /// contents, then immediately recreates an empty directory in its place. This is
    /// typically triggered by the user via the `--clear-cache` CLI flag to force fresh
    /// AI generation across the entire project.
    pub fn clear_cache(&self) -> Result<(), OnboarderError> {
        if self.cache_dir.exists() {
            fs::remove_dir_all(&self.cache_dir)?;
            fs::create_dir_all(&self.cache_dir)?;
        }
        Ok(())
    }

    /// Calculates the total number of currently cached markdown files.
    ///
    /// This function traverses the cache directory and counts all entries that
    /// successfully resolve to a file with a `.md` extension. It gracefully
    /// returns `0` if the directory does not exist or is completely empty.
    pub fn cache_count(&self) -> Result<usize, OnboarderError> {
        if !self.cache_dir.exists() {
            return Ok(0);
        }

        let count = fs::read_dir(&self.cache_dir)?
            .filter_map(|entry| entry.ok())
            .filter(|entry| {
                entry
                    .path()
                    .extension()
                    .and_then(|ext| ext.to_str())
                    .map(|ext| ext == "md")
                    .unwrap_or(false)
            })
            .count();

        Ok(count)
    }
}

/// Generates a cryptographic SHA-256 hash of a file's raw contents.
///
/// Rather than hashing the file path (which would break if the file is moved) or
/// relying on timestamps, this function reads the exact byte contents of the source
/// file and digests it. This ensures that the cache key perfectly represents the
/// state of the code. Even a single character change in the file will produce a
/// completely different hash, intentionally invalidating the old cache.
pub fn hash_file(path: &Path) -> Result<String, OnboarderError> {
    // Read file contents
    let contents = fs::read(path)?;

    // Create SHA-256 hasher
    let mut hasher = Sha256::new();
    hasher.update(&contents);

    // Get the hash result and convert to hex string
    let result = hasher.finalize();
    let hash_hex = result
        .iter()
        .map(|b| format!("{:02x}", b))
        .collect::<String>();

    Ok(hash_hex)
}
